storage:
  dbPath: /data/db

net:
  bindIp: 0.0.0.0
  port: 27017
  tls:
    mode: requireTLS
    certificateKeyFile: /etc/mongo/tls/server.pem
    CAFile: /etc/mongo/tls/ca.crt
    allowConnectionsWithoutCertificates: true

security:
  authorization: enabled